### ISSUE TITLE
SAP Java Connector 3.1 SDK Updates

### ISSUE THREAD

**Issue by qcind** [virtualcry/sapjco-dependency#1]
Dear VirtualCry,

Would you please update the **SAP JCo 3.1 SDK resource with Windows Platform**.
Many thanks.

![jco](https://user-images.githubusercontent.com/3293628/68273233-d6fe9f80-00a0-11ea-80f4-055bd9762050.png)

[SAP JCo 3.1 SDK Resource](https://support.sap.com/en/product/connectors/jco.html)

:)

**Comment by NakiriCr** [comment]
Thanks for your proposal. 
I will upgrade and adapt to the newest sapjco dependency this weekend. After the update, I will inform you again.

**Comment by qcind** [comment]
> Thanks for your proposal.
> I will upgrade and adapt to the newest sapjco dependency this weekend. After the update, I will inform you again.

Thanks for your response.

Here is the  [SAP JCo 3.1.2 SDK Resource](https://github.com/virtualcry/sapjco-dependency/files/3818632/sapjco3-1-2.zip)
