### ISSUE TITLE
Sharing SAP Java Connector 3.0.20 SDK

### ISSUE THREAD

**Issue by qcind** [virtualcry/sapjco-dependency#2]
Sharing SAP Java Connector 3.0.20 SDK

[sapjco3-20.zip](https://github.com/virtualcry/sapjco-dependency/files/3812824/sapjco3-20.zip)

:)

![jco](https://user-images.githubusercontent.com/3293628/68273453-6c9a2f00-00a1-11ea-99dd-76e560a9a671.png)

**Comment by NakiriCr** [comment]
Thanks for your sharing~
